language: java
jdk: 
  - openjdk8
  - oraclejdk9

branches:
  only:
  - master
  - development

before_install: 
  - sudo apt update

install:
  - sudo apt install maven -y

before_script:
  - cd ./seip2020_practical_assignments/

script:
  - mvn package

after_success:
  - echo "Process terminated successfully"

