language: java
jdk: 
  - openjdk8
  - oraclejdk8

branches:
  only:
  - master
  - development

sudo: required

before_install: 
  - sudo apt update

install:
  - sudo apt install maven -y

before_script:
  - seip2020-practical-assignments

script:
  -mvn clean
  -mvn package

after_success:
  - echo "Process terminated successfully"

