language: java
jdk: 
  - openjdk11
 # - oraclejdk9

branches:
  only:
  - master

env:
  global:
  - CODECOV_TOKEN="61987326-962f-4759-8a56-f4b8addaec1f"

before_install: 
  - sudo apt update

install:
  - sudo apt install maven -y

before_script:
  - cd ./seip2020_practical_assignments/

script:
  - mvn clean
  - mvn package jacoco:report

after_success:
  - cd ./../
  - cd ./resources/ 
  - ./test.sh > test_outputs.txt
  - if cat test_outputs.txt | grep "FAILED"; then rm test_outputs.txt; exit 1; else rm test_outputs.txt; echo "Process terminated successfully"; fi
  - bash <(curl -s https://codecov.io/bash)
