language: java
jdk: 
  - openjdk11
 # - oraclejdk9

branches:
  only:
  - master

env:
  global:
  - CODECOV_TOKEN="61987326-962f-4759-8a56-f4b8addaec1f"

before_install: 
  - sudo apt update

install:
  - sudo apt install maven -y

before_script:
  - cd ./seip2020_practical_assignments/

script:
  - mvn clean
  - mvn package jacoco:report

after_success:
  - cd ./../resources/
  - ./.resources/test.sh
  - if ["$(exif ... | tail -1)" == "[FAILED] Integration Test of Source Code Analyzer"]; then exit 1;
  - bash <(curl -s https://codecov.io/bash)
  - echo "Process terminated successfully"
